// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ecoNhom3.Models;

namespace ecoNhom3.Migrations
{
    [DbContext(typeof(MyDbContext))]
    [Migration("20191109063522_ecoNhom3")]
    partial class ecoNhom3
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.6-servicing-10079")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("ecoNhom3.Models.BinhLuanSp", b =>
                {
                    b.Property<int>("MaBl")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("MaHh");

                    b.Property<int>("MaTv");

                    b.Property<int?>("Mahh");

                    b.Property<DateTime?>("NgayBl");

                    b.Property<string>("NoiDung");

                    b.HasKey("MaBl");

                    b.HasIndex("MaTv");

                    b.HasIndex("Mahh");

                    b.ToTable("BinhLuanSps");
                });

            modelBuilder.Entity("ecoNhom3.Models.ChiTietHd", b =>
                {
                    b.Property<int>("MaCTHD")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<double>("DonGia");

                    b.Property<double>("GiamGia");

                    b.Property<int>("MaHd");

                    b.Property<int>("MaHh");

                    b.Property<int?>("Mahd");

                    b.Property<int>("SoLuong");

                    b.HasKey("MaCTHD");

                    b.HasIndex("MaHh");

                    b.HasIndex("Mahd")
                        .IsUnique()
                        .HasFilter("[Mahd] IS NOT NULL");

                    b.ToTable("ChiTietHds");
                });

            modelBuilder.Entity("ecoNhom3.Models.HangHoa", b =>
                {
                    b.Property<int>("MaHh")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<double>("DonGia");

                    b.Property<double>("GiamGia");

                    b.Property<string>("Hinh");

                    b.Property<int>("MaLoai");

                    b.Property<int>("MaNcc");

                    b.Property<string>("MoTa");

                    b.Property<string>("TenHh");

                    b.HasKey("MaHh");

                    b.HasIndex("MaLoai");

                    b.HasIndex("MaNcc");

                    b.ToTable("HangHoas");
                });

            modelBuilder.Entity("ecoNhom3.Models.HoaDon", b =>
                {
                    b.Property<int>("MaHd")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("DiaChi");

                    b.Property<string>("GhiChu");

                    b.Property<string>("HoTen");

                    b.Property<int>("MaTrangThai");

                    b.Property<int>("MaTv");

                    b.Property<DateTime>("NgayDat");

                    b.Property<DateTime?>("NgayGiao");

                    b.Property<double>("PhiShip");

                    b.Property<string>("SdtNguoiNhan");

                    b.HasKey("MaHd");

                    b.HasIndex("MaTrangThai");

                    b.HasIndex("MaTv");

                    b.ToTable("HoaDons");
                });

            modelBuilder.Entity("ecoNhom3.Models.Loai", b =>
                {
                    b.Property<int>("MaLoai")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("TenLoai");

                    b.HasKey("MaLoai");

                    b.ToTable("Loais");
                });

            modelBuilder.Entity("ecoNhom3.Models.NhaCungCap", b =>
                {
                    b.Property<int>("MaNcc")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("DiaChi");

                    b.Property<string>("DienThoai");

                    b.Property<string>("Email");

                    b.Property<string>("MoTa");

                    b.Property<string>("TenNcc");

                    b.HasKey("MaNcc");

                    b.ToTable("NhaCungCaps");
                });

            modelBuilder.Entity("ecoNhom3.Models.PhanLoaiTV", b =>
                {
                    b.Property<int>("LoaiTV")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("LoaiThanhVien");

                    b.HasKey("LoaiTV");

                    b.ToTable("PhanLoaiTVs");
                });

            modelBuilder.Entity("ecoNhom3.Models.ThanhVien", b =>
                {
                    b.Property<int>("MaTv")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("DiaChi");

                    b.Property<string>("DienThoai");

                    b.Property<string>("Email");

                    b.Property<string>("GioiTinh");

                    b.Property<int>("LoaiTv");

                    b.Property<string>("MatKhau");

                    b.Property<DateTime>("NgaySinh");

                    b.Property<string>("TaiKhoan");

                    b.Property<string>("TenTv");

                    b.HasKey("MaTv");

                    b.HasIndex("LoaiTv");

                    b.ToTable("ThanhVien");
                });

            modelBuilder.Entity("ecoNhom3.Models.TrangThai", b =>
                {
                    b.Property<int>("MaTt")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("TenTrangThai");

                    b.HasKey("MaTt");

                    b.ToTable("TrangThais");
                });

            modelBuilder.Entity("ecoNhom3.Models.BinhLuanSp", b =>
                {
                    b.HasOne("ecoNhom3.Models.ThanhVien", "ThanhVien")
                        .WithMany()
                        .HasForeignKey("MaTv")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("ecoNhom3.Models.HangHoa", "HangHoa")
                        .WithMany()
                        .HasForeignKey("Mahh");
                });

            modelBuilder.Entity("ecoNhom3.Models.ChiTietHd", b =>
                {
                    b.HasOne("ecoNhom3.Models.HangHoa", "HangHoa")
                        .WithMany()
                        .HasForeignKey("MaHh")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("ecoNhom3.Models.HoaDon", "HoaDon")
                        .WithOne("ChiTietHd")
                        .HasForeignKey("ecoNhom3.Models.ChiTietHd", "Mahd");
                });

            modelBuilder.Entity("ecoNhom3.Models.HangHoa", b =>
                {
                    b.HasOne("ecoNhom3.Models.Loai", "Loai")
                        .WithMany("HangHoa")
                        .HasForeignKey("MaLoai")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("ecoNhom3.Models.NhaCungCap", "NhaCungCap")
                        .WithMany("HangHoa")
                        .HasForeignKey("MaNcc")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("ecoNhom3.Models.HoaDon", b =>
                {
                    b.HasOne("ecoNhom3.Models.TrangThai", "TrangThai")
                        .WithMany("HoaDon")
                        .HasForeignKey("MaTrangThai")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("ecoNhom3.Models.ThanhVien", "ThanhVien")
                        .WithMany()
                        .HasForeignKey("MaTv")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("ecoNhom3.Models.ThanhVien", b =>
                {
                    b.HasOne("ecoNhom3.Models.PhanLoaiTV", "PhanLoaiTV")
                        .WithMany()
                        .HasForeignKey("LoaiTv")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
